version: '3.8'

# -=-=-=-=-=-=-=-=-=-=VOLUMES=-=-=-=-=-=-=-=-=-=-
volumes:
  data:
  uploads:

# -=-=-=-=-=-=-=-=-=-=NETWORKS=-=-=-=-=-=-=-=-=-=-
networks:
  backend:

services:
# -=-=-=-=-=-=-=-=-=-=FRONTEND=-=-=-=-=-=-=-=-=-=-
  front:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: ./front.dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/front.env
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - back
# -=-=-=-=-=-=-=-=-=-=BACKEND=-=-=-=-=-=-=-=-=-=-
  back:
    volumes:
      - ./backend:/app
      - uploads:/app/image_dir
    build:
      context: ./backend
      dockerfile: ./back.dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - postgres
# -=-=-=-=-=-=-=-=-=-=POSTGRES=-=-=-=-=-=-=-=-=-=-
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - backend
# -=-=-=-=-=-=-=-=-=-=NGINX=-=-=-=-=-=-=-=-=-=-
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4242:4242"
    restart: unless-stopped
    networks:
    - backend
    depends_on:
      - back

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: unless-stopped
#     container_name: nest-pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
#       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#     ports:
#       - '5050:80'
#     depends_on:
#       - postgres
#     networks:
#       - backend