import NavbarA from '../(component)/navbar_auth/navbar_A';
import '../globals.css';
import { Inter } from 'next/font/google';
import styles from './choose.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
	<main>
		<NavbarA navActive={true} testing={true}/>
		<div className={styles.choose}>
			<div className={styles.selection}>
				<div className={styles.select_C}><Link className={styles.link} href="/login" rel='login'>LOGIN</Link></div>
				/
				<div className={styles.select_C}><Link className={styles.link} href="/register" rel='register'>REGISTER</Link></div>
			</div>
			<div className={styles.child}>
				{children}
			</div>
		</div>
	</main>
  );
}
