import NavbarA from './(component)/navbar_auth/navbar_A';
import './globals.css';
import { Inter } from 'next/font/google';
import QueryProvider from './(component)/queryProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
          <body className='body'>
            {children}
          </body>
      </QueryProvider>
    </html>
  )
}
