import './globals.css';
import QueryProvider from './(component)/queryProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
          <body className='body'>
            {children}
          </body>
      </QueryProvider>
    </html>
  )
}
